#!/usr/bin/env sh

command -vp bleachbit 1> /dev/null 2>&1 || {

    printf 'error: missing %s command\n' 'bleachbit' >&2

    exit 1
}

exec bleachbit -so /home/alex/.cache/starship/* 1> /dev/null 2>&1
