# Global directives
dateformat -%d-%m-%Y-%H:%M:%S

# How to react depending on the log file's state
notifempty
missingok

# What do to with the log files.
rotate 2
shred

# Ignore files with some extensions.
tabooext + .bak

# Add drop-in configuration files.
include /home/alex/.config/logrotate.d

# Policies
~/.local/share/xorg/* {
    weekly
    dateext
    create 660 alex alex
}

~/.newsboat/errors.log {
    size 1M
}
