[colors]

; Marengo gray
background-alt = #4C5866

; Gunmetal gray
background = #2A3439

; Cadet gray
foreground = #91A3B0

; Fire engine red
alert = #CE2029

; Self-explanatory
battleshipGray = #848482
pigmentGreen = #00A550
slateGray = #708090
white = #FFFFFF
black = #000000

disabled = #707880
primary = #F0C674


[bar/mango]
width = 100%
height = 28pt
radius = 6

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2pt

border-size = 1pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.battleshipGray}

; Fonts
font-0 = Iosevka:size=12:style=Regular
font-1 = Noto Color Emoji:scale=7.5:style=Regular
font-2 = Font Awesome v4 Compatibility Regular:size=12:style=Regular
font-3 = Font Awesome 6 Brands Regular:size=12:style=Regular
font-4 = Font Awesome 6 Free Regular:size=12:style=Regular
font-5 = Font Awesome 6 Free Solid:size=12:style=Solid

modules-left = xworkspaces
modules-right = uptime pulseaudio backlight battery filesystem memory cpu date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; System tray
tray-position = right
tray-maxsize = 22

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.black}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "🔈 "
format-volume = <label-volume>

label-muted = muted
label-volume = "%percentage%%"
label-muted-foreground = ${colors.disabled}

[module/backlight]
type = internal/backlight

format = <label>

card = intel_backlight

label = "🌞 %percentage%%"

[module/battery]
type = internal/battery

low-at = 25

battery = BAT0

label-low = "🪫 percentage%%"
label-full = "🔋 %percentage%%"
label-charging = "🔌%percentage%%"
label-discharging = "📉 %percentage%%"

[module/filesystem]
type = internal/fs

mount-0 = /

label-mounted = %{F#F0C674}💾 %{F-}%percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

interval = 25

[module/memory]
type = internal/memory

format-prefix = " "
format-prefix-foreground = ${colors.pigmentGreen}

label = %percentage_used:2%%

interval = 1

[module/cpu]
type = internal/cpu

label = %percentage:2%%

format-prefix = " "
format-prefix-foreground = ${colors.white}

interval = 1

[module/date]
type = internal/date

date = 🗓 %d/%m/%Y  %X ⏰

label = %date%
label-foreground = ${colors.white}

interval = 1

[module/uptime]
type = custom/script

exec = /home/alex/Documentos/bashy/src/up

interval = 60

[settings]
screenchange-reload = true
pseudo-transparency = true
