name: "Tests"

on: push

jobs:
  shellcheck:

    runs-on: ubuntu-22.04

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@main

    - name: "Install ShellCheck"
      run: sudo apt-get install shellcheck

    - name: "Check anacron scripts"
      run: shopt -s globstar && shellcheck -S error -f gcc .local/etc/cron.*/*

    - name: "Check custom scripts"
      run: shellcheck -S error -f gcc .local/bin/*

    - name: "Check Bash startup files"
      run: shellcheck -S error -x -f gcc -s bash .bash*

  config-validation:

    runs-on: ubuntu-22.04

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@main

      - name: "systemd user units"
        run: >
          sudo apt-get install duplicity libnotify-bin

          mkdir -pv ~/.local/bin ~/.config/systemd/user

          cp -v .local/bin/* ~/.local/bin

          files=( .config/systemd/user/* )

          cp -v "${files[@]}" ~/.config/systemd/user

          systemctl --user daemon-reload

          systemd-analyze --user verify -- "${files[@]##*/}"

      - name: "rofi"
        run: >
          sudo apt-get install rofi

          mkdir -pv ~/.config/rofi

          grep -vF '@theme' .config/rofi/config.rasi | cp /dev/stdin ~/.config/rofi/config.rasi

          rofi -rasi-validate ~/.config/rofi/config.rasi
