name: "Validation & Checking"

on: push

jobs:
  checking:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@main

      - name: "Install shellcheck"
        run: sudo apt-get install shellcheck

      - name: "Check shell scripts for anacron"
        run: find .local/etc/cron.* -type f -exec shellcheck -S error -f gcc {} \;

      - name: "Check personal shell scripts"
        run: shellcheck -S error -f gcc .local/bin/*

      - name: "Check Bash startup files"
        run: shellcheck -x -S error -f gcc -s bash .bash*

      - name: "Check ZSH startup files"
        run: >
          sudo apt-get install zsh

          zsh -n .zsh*

  validation:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@main

      - name: "Validate user systemd unit files"
        run: >
          sudo apt-get install duplicity libnotify-bin

          mkdir -p ~/.local/bin ~/.config/systemd/user

          cp .local/bin/* ~/.local/bin

          files=( .config/systemd/user/* )

          cp "${files[@]}" ~/.config/systemd/user

          systemctl --user daemon-reload

          systemd-analyze --user verify -- "${files[@]##*/}"

      - name: "Validate rofi configuration file"
        run: >
          sudo apt-get install rofi

          mkdir -p ~/.config/rofi

          grep -vF '@theme' .config/rofi/config.rasi | cp /dev/stdin ~/.config/rofi/config.rasi

          rofi -rasi-validate ~/.config/rofi/config.rasi
